INSERT INTO GENRE(NAME) VALUES ('historical fiction');
INSERT INTO GENRE(NAME) VALUES ('novella');
INSERT INTO GENRE(NAME) VALUES ('fantasy');
INSERT INTO GENRE(NAME) VALUES ('mystery');
INSERT INTO GENRE(NAME) VALUES ('family saga');
INSERT INTO GENRE(NAME) VALUES ('fantasy, children''s fiction');
INSERT INTO GENRE(NAME) VALUES ('adventure');
INSERT INTO GENRE(NAME) VALUES ('detective');
INSERT INTO GENRE(NAME) VALUES ('mystery thriller');
INSERT INTO GENRE(NAME) VALUES ('coming-of-age');
INSERT INTO GENRE(NAME) VALUES ('romance');
INSERT INTO GENRE(NAME) VALUES ('self-help');
INSERT INTO GENRE(NAME) VALUES ('magic realism');
INSERT INTO GENRE(NAME) VALUES ('novel');
INSERT INTO GENRE(NAME) VALUES ('children''s fiction');
INSERT INTO GENRE(NAME) VALUES ('manual');
INSERT INTO GENRE(NAME) VALUES ('children''s novel');
INSERT INTO GENRE(NAME) VALUES ('children''s literature');
INSERT INTO GENRE(NAME) VALUES ('historical novel, mystery');
INSERT INTO GENRE(NAME) VALUES ('war, thriller');
INSERT INTO GENRE(NAME) VALUES ('sexology');
INSERT INTO GENRE(NAME) VALUES ('children''s literature');
INSERT INTO GENRE(NAME) VALUES ('novella, self-help');
INSERT INTO GENRE(NAME) VALUES ('children''s literature, picture book');
INSERT INTO GENRE(NAME) VALUES ('essay/literature');
INSERT INTO GENRE(NAME) VALUES ('southern gothic, bildungsroman');
INSERT INTO GENRE(NAME) VALUES ('gothic horror, family saga');
INSERT INTO GENRE(NAME) VALUES ('popular science, anthropology, astrophysics, cosmology, philosophy, history');
INSERT INTO GENRE(NAME) VALUES ('philosophical novel, young adult');
INSERT INTO GENRE(NAME) VALUES ('mystery-thriller');
INSERT INTO GENRE(NAME) VALUES ('socialist realist novel');
INSERT INTO GENRE(NAME) VALUES ('historical novel');
INSERT INTO GENRE(NAME) VALUES ('historical non-fiction, autobiography, memoir, bildungsroman / coming of age, jewish literature');
INSERT INTO GENRE(NAME) VALUES ('romantic family saga');
INSERT INTO GENRE(NAME) VALUES ('christian literature');
INSERT INTO GENRE(NAME) VALUES ('bildungsroman, historical fiction');
INSERT INTO GENRE(NAME) VALUES ('novel, tragedy');
INSERT INTO GENRE(NAME) VALUES ('gothic novel');
INSERT INTO GENRE(NAME) VALUES ('dystopian, political fiction, social science fiction');
INSERT INTO GENRE(NAME) VALUES ('fiction');
INSERT INTO GENRE(NAME) VALUES ('young adult fiction');
INSERT INTO GENRE(NAME) VALUES ('young adult historical novel');
INSERT INTO GENRE(NAME) VALUES ('self-help, motivational, business fable, psychology, leadership, parable');
INSERT INTO GENRE(NAME) VALUES ('popular science');
INSERT INTO GENRE(NAME) VALUES ('biographical novel');
INSERT INTO GENRE(NAME) VALUES ('new-age spiritual novel');
INSERT INTO GENRE(NAME) VALUES ('young adult romantic novel');
INSERT INTO GENRE(NAME) VALUES ('thriller');
INSERT INTO GENRE(NAME) VALUES ('crime novel');
INSERT INTO GENRE(NAME) VALUES ('romance novel');
INSERT INTO GENRE(NAME) VALUES ('young adult novel, adventure, dystopian, science fiction');
INSERT INTO GENRE(NAME) VALUES ('young adult novel, adventure, war, science fiction, action thriller');
INSERT INTO GENRE(NAME) VALUES ('japanese novel');
INSERT INTO GENRE(NAME) VALUES ('science fiction novel');
INSERT INTO GENRE(NAME) VALUES ('autobiography');
INSERT INTO GENRE(NAME) VALUES ('crime thriller novel');
INSERT INTO GENRE(NAME) VALUES ('war novel');
INSERT INTO GENRE(NAME) VALUES ('unknown');
INSERT INTO GENRE(NAME) VALUES ('satirical allegorical novella, political satire, dystopian fiction, roman à clef');
INSERT INTO GENRE(NAME) VALUES ('semi-autobiographical novel');
INSERT INTO GENRE(NAME) VALUES ('memoir');
INSERT INTO GENRE(NAME) VALUES ('children''s literature, picture book, fiction');
INSERT INTO GENRE(NAME) VALUES ('feminist novel');
INSERT INTO GENRE(NAME) VALUES ('pregnancy guide');
INSERT INTO GENRE(NAME) VALUES ('picaresque novel, bildungsroman, satire, robinsonade');
INSERT INTO GENRE(NAME) VALUES ('young adult novel');
INSERT INTO GENRE(NAME) VALUES ('classic regency novel, romance');
INSERT INTO GENRE(NAME) VALUES ('travel literature');
INSERT INTO GENRE(NAME) VALUES ('unfinished satirical dark comedy novel');
INSERT INTO GENRE(NAME) VALUES ('children''s picture book');
INSERT INTO GENRE(NAME) VALUES ('romantic novel');
INSERT INTO GENRE(NAME) VALUES ('children''s fantasy novel');
INSERT INTO GENRE(NAME) VALUES ('social science, anthropology, psychology');
INSERT INTO GENRE(NAME) VALUES ('coming-of-age murder mystery');
INSERT INTO GENRE(NAME) VALUES ('autobiographical novel');
INSERT INTO GENRE(NAME) VALUES ('young adult fiction');
INSERT INTO GENRE(NAME) VALUES ('historical fiction, war novel');
INSERT INTO GENRE(NAME) VALUES ('erotica');
INSERT INTO GENRE(NAME) VALUES ('science fiction');
INSERT INTO GENRE(NAME) VALUES ('dystopian fiction');
INSERT INTO GENRE(NAME) VALUES ('horror');
